/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/aap2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/aap2.pb-c.h"
void   aap2__aapmessage__init
                     (Aap2__AAPMessage         *message)
{
  static const Aap2__AAPMessage init_value = AAP2__AAPMESSAGE__INIT;
  *message = init_value;
}
size_t aap2__aapmessage__get_packed_size
                     (const Aap2__AAPMessage *message)
{
  assert(message->base.descriptor == &aap2__aapmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__aapmessage__pack
                     (const Aap2__AAPMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__aapmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__aapmessage__pack_to_buffer
                     (const Aap2__AAPMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__aapmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__AAPMessage *
       aap2__aapmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__AAPMessage *)
     protobuf_c_message_unpack (&aap2__aapmessage__descriptor,
                                allocator, len, data);
}
void   aap2__aapmessage__free_unpacked
                     (Aap2__AAPMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__aapmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__welcome__init
                     (Aap2__Welcome         *message)
{
  static const Aap2__Welcome init_value = AAP2__WELCOME__INIT;
  *message = init_value;
}
size_t aap2__welcome__get_packed_size
                     (const Aap2__Welcome *message)
{
  assert(message->base.descriptor == &aap2__welcome__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__welcome__pack
                     (const Aap2__Welcome *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__welcome__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__welcome__pack_to_buffer
                     (const Aap2__Welcome *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__welcome__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__Welcome *
       aap2__welcome__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__Welcome *)
     protobuf_c_message_unpack (&aap2__welcome__descriptor,
                                allocator, len, data);
}
void   aap2__welcome__free_unpacked
                     (Aap2__Welcome *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__welcome__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__connection_config__init
                     (Aap2__ConnectionConfig         *message)
{
  static const Aap2__ConnectionConfig init_value = AAP2__CONNECTION_CONFIG__INIT;
  *message = init_value;
}
size_t aap2__connection_config__get_packed_size
                     (const Aap2__ConnectionConfig *message)
{
  assert(message->base.descriptor == &aap2__connection_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__connection_config__pack
                     (const Aap2__ConnectionConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__connection_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__connection_config__pack_to_buffer
                     (const Aap2__ConnectionConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__connection_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__ConnectionConfig *
       aap2__connection_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__ConnectionConfig *)
     protobuf_c_message_unpack (&aap2__connection_config__descriptor,
                                allocator, len, data);
}
void   aap2__connection_config__free_unpacked
                     (Aap2__ConnectionConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__connection_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__bundle_adu__init
                     (Aap2__BundleADU         *message)
{
  static const Aap2__BundleADU init_value = AAP2__BUNDLE_ADU__INIT;
  *message = init_value;
}
size_t aap2__bundle_adu__get_packed_size
                     (const Aap2__BundleADU *message)
{
  assert(message->base.descriptor == &aap2__bundle_adu__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__bundle_adu__pack
                     (const Aap2__BundleADU *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__bundle_adu__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__bundle_adu__pack_to_buffer
                     (const Aap2__BundleADU *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__bundle_adu__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__BundleADU *
       aap2__bundle_adu__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__BundleADU *)
     protobuf_c_message_unpack (&aap2__bundle_adu__descriptor,
                                allocator, len, data);
}
void   aap2__bundle_adu__free_unpacked
                     (Aap2__BundleADU *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__bundle_adu__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__bundle__init
                     (Aap2__Bundle         *message)
{
  static const Aap2__Bundle init_value = AAP2__BUNDLE__INIT;
  *message = init_value;
}
size_t aap2__bundle__get_packed_size
                     (const Aap2__Bundle *message)
{
  assert(message->base.descriptor == &aap2__bundle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__bundle__pack
                     (const Aap2__Bundle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__bundle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__bundle__pack_to_buffer
                     (const Aap2__Bundle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__bundle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__Bundle *
       aap2__bundle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__Bundle *)
     protobuf_c_message_unpack (&aap2__bundle__descriptor,
                                allocator, len, data);
}
void   aap2__bundle__free_unpacked
                     (Aap2__Bundle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__bundle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__bundle_dispatch_info__init
                     (Aap2__BundleDispatchInfo         *message)
{
  static const Aap2__BundleDispatchInfo init_value = AAP2__BUNDLE_DISPATCH_INFO__INIT;
  *message = init_value;
}
size_t aap2__bundle_dispatch_info__get_packed_size
                     (const Aap2__BundleDispatchInfo *message)
{
  assert(message->base.descriptor == &aap2__bundle_dispatch_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__bundle_dispatch_info__pack
                     (const Aap2__BundleDispatchInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__bundle_dispatch_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__bundle_dispatch_info__pack_to_buffer
                     (const Aap2__BundleDispatchInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__bundle_dispatch_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__BundleDispatchInfo *
       aap2__bundle_dispatch_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__BundleDispatchInfo *)
     protobuf_c_message_unpack (&aap2__bundle_dispatch_info__descriptor,
                                allocator, len, data);
}
void   aap2__bundle_dispatch_info__free_unpacked
                     (Aap2__BundleDispatchInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__bundle_dispatch_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__dispatch_event__init
                     (Aap2__DispatchEvent         *message)
{
  static const Aap2__DispatchEvent init_value = AAP2__DISPATCH_EVENT__INIT;
  *message = init_value;
}
size_t aap2__dispatch_event__get_packed_size
                     (const Aap2__DispatchEvent *message)
{
  assert(message->base.descriptor == &aap2__dispatch_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__dispatch_event__pack
                     (const Aap2__DispatchEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__dispatch_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__dispatch_event__pack_to_buffer
                     (const Aap2__DispatchEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__dispatch_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__DispatchEvent *
       aap2__dispatch_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__DispatchEvent *)
     protobuf_c_message_unpack (&aap2__dispatch_event__descriptor,
                                allocator, len, data);
}
void   aap2__dispatch_event__free_unpacked
                     (Aap2__DispatchEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__dispatch_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__link__init
                     (Aap2__Link         *message)
{
  static const Aap2__Link init_value = AAP2__LINK__INIT;
  *message = init_value;
}
size_t aap2__link__get_packed_size
                     (const Aap2__Link *message)
{
  assert(message->base.descriptor == &aap2__link__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__link__pack
                     (const Aap2__Link *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__link__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__link__pack_to_buffer
                     (const Aap2__Link *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__link__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__Link *
       aap2__link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__Link *)
     protobuf_c_message_unpack (&aap2__link__descriptor,
                                allocator, len, data);
}
void   aap2__link__free_unpacked
                     (Aap2__Link *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__link__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__keepalive__init
                     (Aap2__Keepalive         *message)
{
  static const Aap2__Keepalive init_value = AAP2__KEEPALIVE__INIT;
  *message = init_value;
}
size_t aap2__keepalive__get_packed_size
                     (const Aap2__Keepalive *message)
{
  assert(message->base.descriptor == &aap2__keepalive__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__keepalive__pack
                     (const Aap2__Keepalive *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__keepalive__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__keepalive__pack_to_buffer
                     (const Aap2__Keepalive *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__keepalive__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__Keepalive *
       aap2__keepalive__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__Keepalive *)
     protobuf_c_message_unpack (&aap2__keepalive__descriptor,
                                allocator, len, data);
}
void   aap2__keepalive__free_unpacked
                     (Aap2__Keepalive *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__keepalive__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__aapresponse__init
                     (Aap2__AAPResponse         *message)
{
  static const Aap2__AAPResponse init_value = AAP2__AAPRESPONSE__INIT;
  *message = init_value;
}
size_t aap2__aapresponse__get_packed_size
                     (const Aap2__AAPResponse *message)
{
  assert(message->base.descriptor == &aap2__aapresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__aapresponse__pack
                     (const Aap2__AAPResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__aapresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__aapresponse__pack_to_buffer
                     (const Aap2__AAPResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__aapresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__AAPResponse *
       aap2__aapresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__AAPResponse *)
     protobuf_c_message_unpack (&aap2__aapresponse__descriptor,
                                allocator, len, data);
}
void   aap2__aapresponse__free_unpacked
                     (Aap2__AAPResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__aapresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   aap2__dispatch_result__next_hop_entry__init
                     (Aap2__DispatchResult__NextHopEntry         *message)
{
  static const Aap2__DispatchResult__NextHopEntry init_value = AAP2__DISPATCH_RESULT__NEXT_HOP_ENTRY__INIT;
  *message = init_value;
}
void   aap2__dispatch_result__init
                     (Aap2__DispatchResult         *message)
{
  static const Aap2__DispatchResult init_value = AAP2__DISPATCH_RESULT__INIT;
  *message = init_value;
}
size_t aap2__dispatch_result__get_packed_size
                     (const Aap2__DispatchResult *message)
{
  assert(message->base.descriptor == &aap2__dispatch_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aap2__dispatch_result__pack
                     (const Aap2__DispatchResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aap2__dispatch_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aap2__dispatch_result__pack_to_buffer
                     (const Aap2__DispatchResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aap2__dispatch_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Aap2__DispatchResult *
       aap2__dispatch_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Aap2__DispatchResult *)
     protobuf_c_message_unpack (&aap2__dispatch_result__descriptor,
                                allocator, len, data);
}
void   aap2__dispatch_result__free_unpacked
                     (Aap2__DispatchResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &aap2__dispatch_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor aap2__aapmessage__field_descriptors[6] =
{
  {
    "welcome",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Aap2__AAPMessage, msg_case),
    offsetof(Aap2__AAPMessage, welcome),
    &aap2__welcome__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Aap2__AAPMessage, msg_case),
    offsetof(Aap2__AAPMessage, config),
    &aap2__connection_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adu",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Aap2__AAPMessage, msg_case),
    offsetof(Aap2__AAPMessage, adu),
    &aap2__bundle_adu__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dispatch_event",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Aap2__AAPMessage, msg_case),
    offsetof(Aap2__AAPMessage, dispatch_event),
    &aap2__dispatch_event__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Aap2__AAPMessage, msg_case),
    offsetof(Aap2__AAPMessage, link),
    &aap2__link__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keepalive",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Aap2__AAPMessage, msg_case),
    offsetof(Aap2__AAPMessage, keepalive),
    &aap2__keepalive__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__aapmessage__field_indices_by_name[] = {
  2,   /* field[2] = adu */
  1,   /* field[1] = config */
  3,   /* field[3] = dispatch_event */
  5,   /* field[5] = keepalive */
  4,   /* field[4] = link */
  0,   /* field[0] = welcome */
};
static const ProtobufCIntRange aap2__aapmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor aap2__aapmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.AAPMessage",
  "AAPMessage",
  "Aap2__AAPMessage",
  "aap2",
  sizeof(Aap2__AAPMessage),
  6,
  aap2__aapmessage__field_descriptors,
  aap2__aapmessage__field_indices_by_name,
  1,  aap2__aapmessage__number_ranges,
  (ProtobufCMessageInit) aap2__aapmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__welcome__field_descriptors[1] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__Welcome, node_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__welcome__field_indices_by_name[] = {
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange aap2__welcome__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor aap2__welcome__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.Welcome",
  "Welcome",
  "Aap2__Welcome",
  "aap2",
  sizeof(Aap2__Welcome),
  1,
  aap2__welcome__field_descriptors,
  aap2__welcome__field_indices_by_name,
  1,  aap2__welcome__number_ranges,
  (ProtobufCMessageInit) aap2__welcome__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__connection_config__field_descriptors[5] =
{
  {
    "is_subscriber",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Aap2__ConnectionConfig, is_subscriber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aap2__ConnectionConfig, auth_type),
    &aap2__auth_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secret",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__ConnectionConfig, secret),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endpoint_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__ConnectionConfig, endpoint_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keepalive_seconds",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Aap2__ConnectionConfig, keepalive_seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__connection_config__field_indices_by_name[] = {
  1,   /* field[1] = auth_type */
  3,   /* field[3] = endpoint_id */
  0,   /* field[0] = is_subscriber */
  4,   /* field[4] = keepalive_seconds */
  2,   /* field[2] = secret */
};
static const ProtobufCIntRange aap2__connection_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor aap2__connection_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.ConnectionConfig",
  "ConnectionConfig",
  "Aap2__ConnectionConfig",
  "aap2",
  sizeof(Aap2__ConnectionConfig),
  5,
  aap2__connection_config__field_descriptors,
  aap2__connection_config__field_indices_by_name,
  1,  aap2__connection_config__number_ranges,
  (ProtobufCMessageInit) aap2__connection_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__bundle_adu__field_descriptors[7] =
{
  {
    "src_eid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleADU, src_eid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_eid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleADU, dst_eid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "creation_timestamp_ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleADU, creation_timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleADU, sequence_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_length",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleADU, payload_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adu_flags",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Aap2__BundleADU, n_adu_flags),
    offsetof(Aap2__BundleADU, adu_flags),
    &aap2__bundle_aduflags__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "report_to_eid",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleADU, report_to_eid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__bundle_adu__field_indices_by_name[] = {
  5,   /* field[5] = adu_flags */
  2,   /* field[2] = creation_timestamp_ms */
  1,   /* field[1] = dst_eid */
  4,   /* field[4] = payload_length */
  6,   /* field[6] = report_to_eid */
  3,   /* field[3] = sequence_number */
  0,   /* field[0] = src_eid */
};
static const ProtobufCIntRange aap2__bundle_adu__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor aap2__bundle_adu__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.BundleADU",
  "BundleADU",
  "Aap2__BundleADU",
  "aap2",
  sizeof(Aap2__BundleADU),
  7,
  aap2__bundle_adu__field_descriptors,
  aap2__bundle_adu__field_indices_by_name,
  1,  aap2__bundle_adu__number_ranges,
  (ProtobufCMessageInit) aap2__bundle_adu__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__bundle__field_descriptors[8] =
{
  {
    "src_eid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, src_eid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_eid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, dst_eid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "creation_timestamp_ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, creation_timestamp_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, sequence_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_length",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, payload_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fragment_offset",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, fragment_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_adu_length",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, total_adu_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lifetime_ms",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__Bundle, lifetime_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__bundle__field_indices_by_name[] = {
  2,   /* field[2] = creation_timestamp_ms */
  1,   /* field[1] = dst_eid */
  5,   /* field[5] = fragment_offset */
  7,   /* field[7] = lifetime_ms */
  4,   /* field[4] = payload_length */
  3,   /* field[3] = sequence_number */
  0,   /* field[0] = src_eid */
  6,   /* field[6] = total_adu_length */
};
static const ProtobufCIntRange aap2__bundle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor aap2__bundle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.Bundle",
  "Bundle",
  "Aap2__Bundle",
  "aap2",
  sizeof(Aap2__Bundle),
  8,
  aap2__bundle__field_descriptors,
  aap2__bundle__field_indices_by_name,
  1,  aap2__bundle__number_ranges,
  (ProtobufCMessageInit) aap2__bundle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__bundle_dispatch_info__field_descriptors[8] =
{
  {
    "serialized_size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, serialized_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_frag_size_first",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, min_frag_size_first),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min_frag_size_last",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, min_frag_size_last),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dispatch_time_ms",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, dispatch_time_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiration_time_ms",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, expiration_time_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dispatched_to_node_id",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, dispatched_to_node_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dispatched_to_cla_addr",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, dispatched_to_cla_addr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_bundle_size_bytes",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__BundleDispatchInfo, max_bundle_size_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__bundle_dispatch_info__field_indices_by_name[] = {
  3,   /* field[3] = dispatch_time_ms */
  6,   /* field[6] = dispatched_to_cla_addr */
  5,   /* field[5] = dispatched_to_node_id */
  4,   /* field[4] = expiration_time_ms */
  7,   /* field[7] = max_bundle_size_bytes */
  1,   /* field[1] = min_frag_size_first */
  2,   /* field[2] = min_frag_size_last */
  0,   /* field[0] = serialized_size */
};
static const ProtobufCIntRange aap2__bundle_dispatch_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor aap2__bundle_dispatch_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.BundleDispatchInfo",
  "BundleDispatchInfo",
  "Aap2__BundleDispatchInfo",
  "aap2",
  sizeof(Aap2__BundleDispatchInfo),
  8,
  aap2__bundle_dispatch_info__field_descriptors,
  aap2__bundle_dispatch_info__field_indices_by_name,
  1,  aap2__bundle_dispatch_info__number_ranges,
  (ProtobufCMessageInit) aap2__bundle_dispatch_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__dispatch_event__field_descriptors[3] =
{
  {
    "bundle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Aap2__DispatchEvent, bundle),
    &aap2__bundle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reason",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aap2__DispatchEvent, reason),
    &aap2__dispatch_reason__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "additional_information",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Aap2__DispatchEvent, additional_information),
    &aap2__bundle_dispatch_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__dispatch_event__field_indices_by_name[] = {
  2,   /* field[2] = additional_information */
  0,   /* field[0] = bundle */
  1,   /* field[1] = reason */
};
static const ProtobufCIntRange aap2__dispatch_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor aap2__dispatch_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.DispatchEvent",
  "DispatchEvent",
  "Aap2__DispatchEvent",
  "aap2",
  sizeof(Aap2__DispatchEvent),
  3,
  aap2__dispatch_event__field_descriptors,
  aap2__dispatch_event__field_indices_by_name,
  1,  aap2__dispatch_event__number_ranges,
  (ProtobufCMessageInit) aap2__dispatch_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__link__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aap2__Link, status),
    &aap2__link_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_node_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__Link, peer_node_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_cla_addr",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__Link, peer_cla_addr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flag",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aap2__Link, flag),
    &aap2__link_flags__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__link__field_indices_by_name[] = {
  3,   /* field[3] = flag */
  2,   /* field[2] = peer_cla_addr */
  1,   /* field[1] = peer_node_id */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange aap2__link__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor aap2__link__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.Link",
  "Link",
  "Aap2__Link",
  "aap2",
  sizeof(Aap2__Link),
  4,
  aap2__link__field_descriptors,
  aap2__link__field_indices_by_name,
  1,  aap2__link__number_ranges,
  (ProtobufCMessageInit) aap2__link__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define aap2__keepalive__field_descriptors NULL
#define aap2__keepalive__field_indices_by_name NULL
#define aap2__keepalive__number_ranges NULL
const ProtobufCMessageDescriptor aap2__keepalive__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.Keepalive",
  "Keepalive",
  "Aap2__Keepalive",
  "aap2",
  sizeof(Aap2__Keepalive),
  0,
  aap2__keepalive__field_descriptors,
  aap2__keepalive__field_indices_by_name,
  0,  aap2__keepalive__number_ranges,
  (ProtobufCMessageInit) aap2__keepalive__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__aapresponse__field_descriptors[3] =
{
  {
    "response_status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Aap2__AAPResponse, response_status),
    &aap2__response_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dispatch_result",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Aap2__AAPResponse, dispatch_result),
    &aap2__dispatch_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bundle_headers",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Aap2__AAPResponse, bundle_headers),
    &aap2__bundle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__aapresponse__field_indices_by_name[] = {
  2,   /* field[2] = bundle_headers */
  1,   /* field[1] = dispatch_result */
  0,   /* field[0] = response_status */
};
static const ProtobufCIntRange aap2__aapresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor aap2__aapresponse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.AAPResponse",
  "AAPResponse",
  "Aap2__AAPResponse",
  "aap2",
  sizeof(Aap2__AAPResponse),
  3,
  aap2__aapresponse__field_descriptors,
  aap2__aapresponse__field_indices_by_name,
  1,  aap2__aapresponse__number_ranges,
  (ProtobufCMessageInit) aap2__aapresponse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__dispatch_result__next_hop_entry__field_descriptors[3] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Aap2__DispatchResult__NextHopEntry, node_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fragment_offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__DispatchResult__NextHopEntry, fragment_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fragment_length",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Aap2__DispatchResult__NextHopEntry, fragment_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__dispatch_result__next_hop_entry__field_indices_by_name[] = {
  2,   /* field[2] = fragment_length */
  1,   /* field[1] = fragment_offset */
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange aap2__dispatch_result__next_hop_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor aap2__dispatch_result__next_hop_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.DispatchResult.NextHopEntry",
  "NextHopEntry",
  "Aap2__DispatchResult__NextHopEntry",
  "aap2",
  sizeof(Aap2__DispatchResult__NextHopEntry),
  3,
  aap2__dispatch_result__next_hop_entry__field_descriptors,
  aap2__dispatch_result__next_hop_entry__field_indices_by_name,
  1,  aap2__dispatch_result__next_hop_entry__number_ranges,
  (ProtobufCMessageInit) aap2__dispatch_result__next_hop_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor aap2__dispatch_result__field_descriptors[1] =
{
  {
    "next_hops",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Aap2__DispatchResult, n_next_hops),
    offsetof(Aap2__DispatchResult, next_hops),
    &aap2__dispatch_result__next_hop_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aap2__dispatch_result__field_indices_by_name[] = {
  0,   /* field[0] = next_hops */
};
static const ProtobufCIntRange aap2__dispatch_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor aap2__dispatch_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aap2.DispatchResult",
  "DispatchResult",
  "Aap2__DispatchResult",
  "aap2",
  sizeof(Aap2__DispatchResult),
  1,
  aap2__dispatch_result__field_descriptors,
  aap2__dispatch_result__field_indices_by_name,
  1,  aap2__dispatch_result__number_ranges,
  (ProtobufCMessageInit) aap2__dispatch_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue aap2__auth_type__enum_values_by_number[4] =
{
  { "AUTH_TYPE_DEFAULT", "AAP2__AUTH_TYPE__AUTH_TYPE_DEFAULT", 0 },
  { "AUTH_TYPE_FIB_CONTROL", "AAP2__AUTH_TYPE__AUTH_TYPE_FIB_CONTROL", 1 },
  { "AUTH_TYPE_BUNDLE_DISPATCH", "AAP2__AUTH_TYPE__AUTH_TYPE_BUNDLE_DISPATCH", 2 },
  { "AUTH_TYPE_FIB_AND_DISPATCH", "AAP2__AUTH_TYPE__AUTH_TYPE_FIB_AND_DISPATCH", 3 },
};
static const ProtobufCIntRange aap2__auth_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex aap2__auth_type__enum_values_by_name[4] =
{
  { "AUTH_TYPE_BUNDLE_DISPATCH", 2 },
  { "AUTH_TYPE_DEFAULT", 0 },
  { "AUTH_TYPE_FIB_AND_DISPATCH", 3 },
  { "AUTH_TYPE_FIB_CONTROL", 1 },
};
const ProtobufCEnumDescriptor aap2__auth_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aap2.AuthType",
  "AuthType",
  "Aap2__AuthType",
  "aap2",
  4,
  aap2__auth_type__enum_values_by_number,
  4,
  aap2__auth_type__enum_values_by_name,
  1,
  aap2__auth_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aap2__bundle_aduflags__enum_values_by_number[4] =
{
  { "BUNDLE_ADU_NORMAL", "AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_NORMAL", 0 },
  { "BUNDLE_ADU_BPDU", "AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_BPDU", 1 },
  { "BUNDLE_ADU_WITH_BDM_AUTH", "AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_WITH_BDM_AUTH", 2 },
  { "BUNDLE_ADU_STATUS_REPORT", "AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_STATUS_REPORT", 3 },
};
static const ProtobufCIntRange aap2__bundle_aduflags__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex aap2__bundle_aduflags__enum_values_by_name[4] =
{
  { "BUNDLE_ADU_BPDU", 1 },
  { "BUNDLE_ADU_NORMAL", 0 },
  { "BUNDLE_ADU_STATUS_REPORT", 3 },
  { "BUNDLE_ADU_WITH_BDM_AUTH", 2 },
};
const ProtobufCEnumDescriptor aap2__bundle_aduflags__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aap2.BundleADUFlags",
  "BundleADUFlags",
  "Aap2__BundleADUFlags",
  "aap2",
  4,
  aap2__bundle_aduflags__enum_values_by_number,
  4,
  aap2__bundle_aduflags__enum_values_by_name,
  1,
  aap2__bundle_aduflags__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aap2__dispatch_reason__enum_values_by_number[6] =
{
  { "DISPATCH_REASON_UNSPECIFIED", "AAP2__DISPATCH_REASON__DISPATCH_REASON_UNSPECIFIED", 0 },
  { "DISPATCH_REASON_NO_FIB_ENTRY", "AAP2__DISPATCH_REASON__DISPATCH_REASON_NO_FIB_ENTRY", 1 },
  { "DISPATCH_REASON_LINK_INACTIVE", "AAP2__DISPATCH_REASON__DISPATCH_REASON_LINK_INACTIVE", 2 },
  { "DISPATCH_REASON_CLA_ENQUEUE_FAILED", "AAP2__DISPATCH_REASON__DISPATCH_REASON_CLA_ENQUEUE_FAILED", 3 },
  { "DISPATCH_REASON_TX_FAILED", "AAP2__DISPATCH_REASON__DISPATCH_REASON_TX_FAILED", 4 },
  { "DISPATCH_REASON_TX_SUCCEEDED", "AAP2__DISPATCH_REASON__DISPATCH_REASON_TX_SUCCEEDED", 5 },
};
static const ProtobufCIntRange aap2__dispatch_reason__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex aap2__dispatch_reason__enum_values_by_name[6] =
{
  { "DISPATCH_REASON_CLA_ENQUEUE_FAILED", 3 },
  { "DISPATCH_REASON_LINK_INACTIVE", 2 },
  { "DISPATCH_REASON_NO_FIB_ENTRY", 1 },
  { "DISPATCH_REASON_TX_FAILED", 4 },
  { "DISPATCH_REASON_TX_SUCCEEDED", 5 },
  { "DISPATCH_REASON_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor aap2__dispatch_reason__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aap2.DispatchReason",
  "DispatchReason",
  "Aap2__DispatchReason",
  "aap2",
  6,
  aap2__dispatch_reason__enum_values_by_number,
  6,
  aap2__dispatch_reason__enum_values_by_name,
  1,
  aap2__dispatch_reason__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aap2__link_status__enum_values_by_number[4] =
{
  { "LINK_STATUS_UNSPECIFIED", "AAP2__LINK_STATUS__LINK_STATUS_UNSPECIFIED", 0 },
  { "LINK_STATUS_UP", "AAP2__LINK_STATUS__LINK_STATUS_UP", 3 },
  { "LINK_STATUS_DOWN", "AAP2__LINK_STATUS__LINK_STATUS_DOWN", 4 },
  { "LINK_STATUS_DROP_CLA_MAPPING", "AAP2__LINK_STATUS__LINK_STATUS_DROP_CLA_MAPPING", 5 },
};
static const ProtobufCIntRange aap2__link_status__value_ranges[] = {
{0, 0},{3, 1},{0, 4}
};
static const ProtobufCEnumValueIndex aap2__link_status__enum_values_by_name[4] =
{
  { "LINK_STATUS_DOWN", 2 },
  { "LINK_STATUS_DROP_CLA_MAPPING", 3 },
  { "LINK_STATUS_UNSPECIFIED", 0 },
  { "LINK_STATUS_UP", 1 },
};
const ProtobufCEnumDescriptor aap2__link_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aap2.LinkStatus",
  "LinkStatus",
  "Aap2__LinkStatus",
  "aap2",
  4,
  aap2__link_status__enum_values_by_number,
  4,
  aap2__link_status__enum_values_by_name,
  2,
  aap2__link_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aap2__link_flags__enum_values_by_number[2] =
{
  { "LINK_FLAG_NONE", "AAP2__LINK_FLAGS__LINK_FLAG_NONE", 0 },
  { "LINK_FLAG_DIRECT", "AAP2__LINK_FLAGS__LINK_FLAG_DIRECT", 1 },
};
static const ProtobufCIntRange aap2__link_flags__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex aap2__link_flags__enum_values_by_name[2] =
{
  { "LINK_FLAG_DIRECT", 1 },
  { "LINK_FLAG_NONE", 0 },
};
const ProtobufCEnumDescriptor aap2__link_flags__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aap2.LinkFlags",
  "LinkFlags",
  "Aap2__LinkFlags",
  "aap2",
  2,
  aap2__link_flags__enum_values_by_number,
  2,
  aap2__link_flags__enum_values_by_name,
  1,
  aap2__link_flags__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue aap2__response_status__enum_values_by_number[8] =
{
  { "RESPONSE_STATUS_UNSPECIFIED", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_UNSPECIFIED", 0 },
  { "RESPONSE_STATUS_SUCCESS", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_SUCCESS", 1 },
  { "RESPONSE_STATUS_ACK", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_ACK", 2 },
  { "RESPONSE_STATUS_ERROR", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_ERROR", 8 },
  { "RESPONSE_STATUS_TIMEOUT", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_TIMEOUT", 9 },
  { "RESPONSE_STATUS_INVALID_REQUEST", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_INVALID_REQUEST", 10 },
  { "RESPONSE_STATUS_NOT_FOUND", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_NOT_FOUND", 11 },
  { "RESPONSE_STATUS_UNAUTHORIZED", "AAP2__RESPONSE_STATUS__RESPONSE_STATUS_UNAUTHORIZED", 12 },
};
static const ProtobufCIntRange aap2__response_status__value_ranges[] = {
{0, 0},{8, 3},{0, 8}
};
static const ProtobufCEnumValueIndex aap2__response_status__enum_values_by_name[8] =
{
  { "RESPONSE_STATUS_ACK", 2 },
  { "RESPONSE_STATUS_ERROR", 3 },
  { "RESPONSE_STATUS_INVALID_REQUEST", 5 },
  { "RESPONSE_STATUS_NOT_FOUND", 6 },
  { "RESPONSE_STATUS_SUCCESS", 1 },
  { "RESPONSE_STATUS_TIMEOUT", 4 },
  { "RESPONSE_STATUS_UNAUTHORIZED", 7 },
  { "RESPONSE_STATUS_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor aap2__response_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "aap2.ResponseStatus",
  "ResponseStatus",
  "Aap2__ResponseStatus",
  "aap2",
  8,
  aap2__response_status__enum_values_by_number,
  8,
  aap2__response_status__enum_values_by_name,
  2,
  aap2__response_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
