/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/aap2.proto */

#ifndef PROTOBUF_C_proto_2faap2_2eproto__INCLUDED
#define PROTOBUF_C_proto_2faap2_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Aap2__AAPMessage Aap2__AAPMessage;
typedef struct Aap2__Welcome Aap2__Welcome;
typedef struct Aap2__ConnectionConfig Aap2__ConnectionConfig;
typedef struct Aap2__BundleADU Aap2__BundleADU;
typedef struct Aap2__Bundle Aap2__Bundle;
typedef struct Aap2__BundleDispatchInfo Aap2__BundleDispatchInfo;
typedef struct Aap2__DispatchEvent Aap2__DispatchEvent;
typedef struct Aap2__Link Aap2__Link;
typedef struct Aap2__Keepalive Aap2__Keepalive;
typedef struct Aap2__AAPResponse Aap2__AAPResponse;
typedef struct Aap2__DispatchResult Aap2__DispatchResult;
typedef struct Aap2__DispatchResult__NextHopEntry Aap2__DispatchResult__NextHopEntry;


/* --- enums --- */

/*
 * The type of actions requested to be enabled for an AAP 2.0 connection.
 */
typedef enum _Aap2__AuthType {
  /*
   * Only allow to register free endpoints or agent IDs for which the same
   * secret can be provided.
   */
  AAP2__AUTH_TYPE__AUTH_TYPE_DEFAULT = 0,
  /*
   * Allow for changing the FIB (non-sub) or receiving FIB updates (sub).
   */
  AAP2__AUTH_TYPE__AUTH_TYPE_FIB_CONTROL = 1,
  /*
   * Allow for dispatching bundles (sub) or sending bundles with the flag
   * `BUNDLE_ADU_WITH_BDM_AUTH` (non-sub).
   */
  AAP2__AUTH_TYPE__AUTH_TYPE_BUNDLE_DISPATCH = 2,
  /*
   * Allow for receiving FIB updates and dispatching bundles.
   */
  AAP2__AUTH_TYPE__AUTH_TYPE_FIB_AND_DISPATCH = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAP2__AUTH_TYPE)
} Aap2__AuthType;
/*
 * Flags defining specific behavior for the bundle ADU, e.g., for BIBE.
 */
typedef enum _Aap2__BundleADUFlags {
  /*
   * No flags set - normal transmission request.
   */
  AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_NORMAL = 0,
  /*
   * The bundle ADU is a BIBE protocol data unit - request BIBE transmission.
   */
  AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_BPDU = 1,
  /*
   * The client that sent the ADU is authenticated as BDM and this can be
   * ensured by µD3TN. If set when sending ADUs, this requests µD3TN to
   * check this condition and associate the ADU with the given flag, such that
   * it is set when the ADU is received (locally) again. If set in a received
   * ADU, it has been ensured by µD3TN that the sender has been authenticated
   * appropriately. This can be used to securely implement clients that perform
   * administrative actions (e.g., configuring contacts in a BDM).
   */
  AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_WITH_BDM_AUTH = 2,
  /*
   * The (incoming) bundle ADU is a bundle status report.
   */
  AAP2__BUNDLE_ADUFLAGS__BUNDLE_ADU_STATUS_REPORT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAP2__BUNDLE_ADUFLAGS)
} Aap2__BundleADUFlags;
/*
 * The reason why a DispatchEvent was triggered.
 */
typedef enum _Aap2__DispatchReason {
  /*
   * Invalid.
   */
  AAP2__DISPATCH_REASON__DISPATCH_REASON_UNSPECIFIED = 0,
  /*
   * No direct-dispatch link was found for the destination EID in the FIB.
   */
  AAP2__DISPATCH_REASON__DISPATCH_REASON_NO_FIB_ENTRY = 1,
  /*
   * The link that should be used is currently not active or unusable.
   */
  AAP2__DISPATCH_REASON__DISPATCH_REASON_LINK_INACTIVE = 2,
  /*
   * The CLA subsystem responded negatively to the next-hop TX request or no
   * applicable CLA and link could be determined for the given fragment.
   */
  AAP2__DISPATCH_REASON__DISPATCH_REASON_CLA_ENQUEUE_FAILED = 3,
  /*
   * The transmission was attempted by the CLA, but failed.
   */
  AAP2__DISPATCH_REASON__DISPATCH_REASON_TX_FAILED = 4,
  /*
   * The CLA transmission succeeded (this is an information to the BDM).
   * Note that this may concern the whole bundle (if determined to be sent
   * completely), or just a single fragment.
   */
  AAP2__DISPATCH_REASON__DISPATCH_REASON_TX_SUCCEEDED = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAP2__DISPATCH_REASON)
} Aap2__DispatchReason;
/*
 * The intended or currently-recorded status of a Link in the FIB.
 */
typedef enum _Aap2__LinkStatus {
  /*
   * Request: Invalid.
   * Reply: The link has been requested (e.g., via AAP) but the CLA has not yet
   * confirmed a connection (first status for scheduled links).
   */
  AAP2__LINK_STATUS__LINK_STATUS_UNSPECIFIED = 0,
  /*
   * The link is present and available for forwarding bundles. Can also be used
   * to add a node ID mapping.
   */
  AAP2__LINK_STATUS__LINK_STATUS_UP = 3,
  /*
   * Request: Deletion of the link and all node mappings is requested.
   * Reply: The link has been marked as down.
   */
  AAP2__LINK_STATUS__LINK_STATUS_DOWN = 4,
  /*
   * Request: Deletion of the node-to-cla-address mapping is requested.
   * Reply: Invalid.
   */
  AAP2__LINK_STATUS__LINK_STATUS_DROP_CLA_MAPPING = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAP2__LINK_STATUS)
} Aap2__LinkStatus;
/*
 * Additional properties that can be assigned to a Link.
 */
typedef enum _Aap2__LinkFlags {
  /*
   * No additional flags are assigned to the Link.
   */
  AAP2__LINK_FLAGS__LINK_FLAG_NONE = 0,
  /*
   * A Link that will be directly used, without dispatching through a BDM, in
   * case the destination node ID was resolved to it and its status is ACTIVE.
   */
  AAP2__LINK_FLAGS__LINK_FLAG_DIRECT = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAP2__LINK_FLAGS)
} Aap2__LinkFlags;
/*
 * Definition of the status codes for an AAPResponse to be associated with.
 */
typedef enum _Aap2__ResponseStatus {
  /*
   * Invalid.
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_UNSPECIFIED = 0,
  /*
   * Success.
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_SUCCESS = 1,
  /*
   * Data received (neither success nor failure can be indicated).
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_ACK = 2,
  /*
   * Failure status: all values >= 8.
   * An unspecified failure.
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_ERROR = 8,
  /*
   * A timeout occurred when performing the requested action.
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_TIMEOUT = 9,
  /*
   * The received request is considered invalid and, thus, is not processed.
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_INVALID_REQUEST = 10,
  /*
   * A resource required for processing the request was not found.
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_NOT_FOUND = 11,
  /*
   * The Client is not authorized to perform the requested action or a provided
   * credential value is not valid for the requested authorization.
   */
  AAP2__RESPONSE_STATUS__RESPONSE_STATUS_UNAUTHORIZED = 12
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAP2__RESPONSE_STATUS)
} Aap2__ResponseStatus;

/* --- messages --- */

typedef enum {
  AAP2__AAPMESSAGE__MSG__NOT_SET = 0,
  AAP2__AAPMESSAGE__MSG_WELCOME = 1,
  AAP2__AAPMESSAGE__MSG_CONFIG = 2,
  AAP2__AAPMESSAGE__MSG_ADU = 3,
  AAP2__AAPMESSAGE__MSG_DISPATCH_EVENT = 4,
  AAP2__AAPMESSAGE__MSG_LINK = 5,
  AAP2__AAPMESSAGE__MSG_KEEPALIVE = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(AAP2__AAPMESSAGE__MSG__CASE)
} Aap2__AAPMessage__MsgCase;

/*
 * The outer AAP 2.0 message type that is always sent by the Initiator (the
 * Client if configured with `is_subscriber == false`, otherwise the Server).
 */
struct  Aap2__AAPMessage
{
  ProtobufCMessage base;
  Aap2__AAPMessage__MsgCase msg_case;
  union {
    /*
     * Message transmitting a bundle ADU into either direction.
     */
    Aap2__BundleADU *adu;
    /*
     * Message sent by the Client to authenticate itself and configure the
     * connection.
     */
    Aap2__ConnectionConfig *config;
    /*
     * Message informing a BDM Client about a relevant bundle status change,
     * allowing it to be (re)dispatched in response.
     */
    Aap2__DispatchEvent *dispatch_event;
    /*
     * Call issued regularly to ensure the connection is still alive.
     */
    Aap2__Keepalive *keepalive;
    /*
     * Message for initiating or informing about CLA link status changes.
     * This message is also issued multiple times by µD3TN at the start of a
     * connection to a FIB-authorized subscriber to transmit the current FIB.
     */
    Aap2__Link *link;
    /*
     * Message sent by the Server at the start of a connection to
     * communicate basic parameters.
     */
    Aap2__Welcome *welcome;
  };
};
#define AAP2__AAPMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__aapmessage__descriptor) \
, AAP2__AAPMESSAGE__MSG__NOT_SET, {0} }


/*
 * Message sent by the Server at the start of a connection to
 * communicate basic parameters.
 */
struct  Aap2__Welcome
{
  ProtobufCMessage base;
  /*
   * The local node ID, i.e., the (primary) EID identifying the local node.
   * This may become a repeated element in the future.
   * This value shall be used for deriving the (requested) application EIDs.
   */
  char *node_id;
};
#define AAP2__WELCOME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__welcome__descriptor) \
, (char *)protobuf_c_empty_string }


/*
 * Message sent by the Client to authenticate itself and configure the
 * connection.
 */
struct  Aap2__ConnectionConfig
{
  ProtobufCMessage base;
  /*
   * If `true`, the direction of control is switched after positive
   * confirmation, i.e., the Server becomes the Initiator of all following
   * communication and also takes over sending the Keepalive messages.
   */
  protobuf_c_boolean is_subscriber;
  /*
   * Controls the actions allowed and data provided over the connection.
   */
  Aap2__AuthType auth_type;
  /*
   * A secret to authorize the configuration. Required for already-registered
   * endpoints and if `auth_type != 0`. When creating a new registration, this
   * field is optional, but only if it is set, the same registration can be
   * claimed by other connections (that need to specify the same secret).
   * If `auth_type != 0`, the secret must be equal to the configured
   * pre-shared key for allowing the requested access.
   */
  char *secret;
  /*
   * The endpoint to be registered for the app. This is required to be a full
   * EID as the local node may have multiple node IDs that can be used for
   * registering applications. Optional when `auth_type != 0` and the app.
   * only intends to control the FIB or dispatch bundles.
   */
  char *endpoint_id;
  /*
   * The maximum time interval between messages, should be zero, or between
   * 30 sec and 600 sec. The Initiator SHALL send `KEEPALIVE` messages after
   * this amount of time has elapsed. 0 disables the feature (see RFC 9174),
   * which is useful e.g. for local sockets. Default = 0 (disabled).
   */
  uint32_t keepalive_seconds;
};
#define AAP2__CONNECTION_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__connection_config__descriptor) \
, 0, AAP2__AUTH_TYPE__AUTH_TYPE_DEFAULT, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * Message transmitting a bundle ADU into either direction.
 */
struct  Aap2__BundleADU
{
  ProtobufCMessage base;
  /*
   * The bundle source EID. Optional when sending the bundle from the only
   * registered endpoint associated with the connection.
   * NOTE: FUTURE EXTENSION: Specifies the used local endpoint if multiple
   * endpoints can be registered (and have been registered).
   */
  char *src_eid;
  /*
   * The bundle destination EID.
   */
  char *dst_eid;
  /*
   * The report-to EID. NOTE: Only supported when sending bundles.
   * If this field is set, µD3TN automatically requests all status reports.
   */
  char *report_to_eid;
  /*
   * The bundle creation time in milliseconds since the DTN epoch as defined
   * in RFC 9171. Optional when sending bundles (will be assigned by µD3TN).
   */
  uint64_t creation_timestamp_ms;
  /*
   * The bundle sequence number as defined in RFC 9171.
   * Optional when sending bundles (will be assigned by µD3TN).
   */
  uint64_t sequence_number;
  /*
   * The number of bytes contained in the bundle payload, which MUST be
   * enclosed immediately _after_ the Protobuf message.
   */
  uint64_t payload_length;
  /*
   * Flags defining specific behavior for the bundle ADU, e.g., for BIBE.
   */
  size_t n_adu_flags;
  Aap2__BundleADUFlags *adu_flags;
};
#define AAP2__BUNDLE_ADU__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__bundle_adu__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0,NULL }


/*
 * Message informing a BDM Client about a received or newly-created
 * bundle.
 */
struct  Aap2__Bundle
{
  ProtobufCMessage base;
  /*
   * The bundle source EID.
   */
  char *src_eid;
  /*
   * The bundle destination EID.
   */
  char *dst_eid;
  /*
   * The bundle creation time in milliseconds since the DTN epoch as defined
   * in RFC 9171.
   */
  uint64_t creation_timestamp_ms;
  /*
   * The bundle sequence number as defined in RFC 9171.
   */
  uint64_t sequence_number;
  /*
   * The payload length as defined in RFC 9171.
   */
  uint64_t payload_length;
  /*
   * The fragment offset as defined in RFC 9171.
   * Only set if the bundle is a fragment.
   */
  uint64_t fragment_offset;
  /*
   * The total ADU length as defined in RFC 9171.
   * Only set if the bundle is a fragment.
   */
  uint64_t total_adu_length;
  /*
   * The bundle lifetime as defined in RFC 9171.
   */
  uint64_t lifetime_ms;
};
#define AAP2__BUNDLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__bundle__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0 }


/*
 * Message providing more information about the bundle to be dispatched, e.g.,
 * how large its wire representation and minimum fragment size are.
 */
struct  Aap2__BundleDispatchInfo
{
  ProtobufCMessage base;
  /*
   * The amount of bytes that a wire representation of the bundle requires.
   */
  uint64_t serialized_size;
  /*
   * The minimum size, in bytes, of the first bundle fragment, if fragmentation
   * is considered by the BDM. The first fragment contains all extension blocks
   * and, thus, always has a larger minimum size. If the bundle must not be
   * fragmented, this is equal to the serialized size of the bundle.
   */
  uint64_t min_frag_size_first;
  /*
   * The minimum size, in bytes, of other bundle fragments, if fragmentation
   * is considered by the BDM. If the bundle must not be fragmented, this is
   * equal to zero.
   */
  uint64_t min_frag_size_last;
  /*
   * The DTN timestamp at which the dispatch event was generated.
   */
  uint64_t dispatch_time_ms;
  /*
   * The DTN timestamp after which bundle expiration is assumed.
   */
  uint64_t expiration_time_ms;
  /*
   * The node ID that the bundle was previously dispatched to. Only set in case
   * the DispatchEvent reports TX success/failure.
   */
  char *dispatched_to_node_id;
  /*
   * The CLA address that the bundle was previously dispatched to. Only set in
   * case the DispatchEvent reports TX success/failure.
   */
  char *dispatched_to_cla_addr;
  /*
   * The largest size of a bundle, including BP headers, that can reliably be
   * sent via the initialized CLAs. This value is determined as the minimum of
   * the maximum bundle sizes reported by all loaded CLAs and the maximum
   * bundle size specified on the command line. If set to zero, a maximum
   * bundle size of 2^64 bytes should be assumed. µD3TN will automatically
   * attempt to fragment bundles larger than the maximum bundle size.
   */
  uint64_t max_bundle_size_bytes;
};
#define AAP2__BUNDLE_DISPATCH_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__bundle_dispatch_info__descriptor) \
, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * Message informing a BDM Client about a relevant bundle status change,
 * allowing it to be (re)dispatched in response.
 * Note that this may concern a whole bundle or just a single fragment after
 * a BDM has requested fragmentation. Not in all cases dispatching is required
 * (e.g., in the case of the "TX_SUCCEEDED" reason code, it is often not
 * desired to dispatch the bundle again).
 */
struct  Aap2__DispatchEvent
{
  ProtobufCMessage base;
  /*
   * The bundle to dispatch. Note that this refers to the original bundle when
   * reporting TX success/failure for previously-created fragments.
   */
  Aap2__Bundle *bundle;
  /*
   * Specifies why the BDM is triggered this time.
   */
  Aap2__DispatchReason reason;
  /*
   * Provides additional information about the dispatch event and the bundle.
   */
  Aap2__BundleDispatchInfo *additional_information;
};
#define AAP2__DISPATCH_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__dispatch_event__descriptor) \
, NULL, AAP2__DISPATCH_REASON__DISPATCH_REASON_UNSPECIFIED, NULL }


/*
 * Message for initiating or informing about CLA link status changes.
 */
struct  Aap2__Link
{
  ProtobufCMessage base;
  /*
   * The intended or detected link status.
   */
  Aap2__LinkStatus status;
  /*
   * An EID representing the next-hop node ID.
   */
  char *peer_node_id;
  /*
   * The identification of a CLA plus CLA-specific address to reach the
   * next-hop bundle node.
   */
  char *peer_cla_addr;
  /*
   * Additional properties assigned to this Link.
   */
  Aap2__LinkFlags flag;
};
#define AAP2__LINK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__link__descriptor) \
, AAP2__LINK_STATUS__LINK_STATUS_UNSPECIFIED, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, AAP2__LINK_FLAGS__LINK_FLAG_NONE }


/*
 * A message that should be regularly sent by the current Initiator and must be
 * acknowledged with an `AAPResponse` specifying `RESPONSE_STATUS_ACK`.
 */
struct  Aap2__Keepalive
{
  ProtobufCMessage base;
};
#define AAP2__KEEPALIVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__keepalive__descriptor) \
 }


/*
 * The response to every AAPMessage, sent by the peer that received the message.
 */
struct  Aap2__AAPResponse
{
  ProtobufCMessage base;
  /*
   * The result of the received call/request represented as a single value.
   */
  Aap2__ResponseStatus response_status;
  /*
   * Set the next hops for a bundle. Only valid in response to a Bundle
   * message sent to a BDM by the server (µD3TN).
   */
  Aap2__DispatchResult *dispatch_result;
  /*
   * Headers of the created bundle (present when sending a bundle).
   */
  Aap2__Bundle *bundle_headers;
};
#define AAP2__AAPRESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__aapresponse__descriptor) \
, AAP2__RESPONSE_STATUS__RESPONSE_STATUS_UNSPECIFIED, NULL, NULL }


/*
 * Representation of an entry in the list of next hops for a bundle.
 * Used for communicating the list of next hops and fragmentation instructions
 * in response to a DispatchEvent.
 */
struct  Aap2__DispatchResult__NextHopEntry
{
  ProtobufCMessage base;
  /*
   * The next-hop node ID for the bundle. May be an ID such as "ud3tn:storage"
   * that resolves to a special CLA.
   */
  char *node_id;
  /*
   * The fragment offset for the fragment to be sent, as defined in RFC 9171.
   * Note that this field represents the absolute offset - if the bundle to be
   * dispatched was already a fragment, it represents the total fragment
   * offset as it will be specified in the resulting bundle primary block.
   * Only set if the bundle to be sent is a fragment.
   */
  uint64_t fragment_offset;
  /*
   * The length of the fragment to be sent.
   * Only set if the bundle to be sent is a fragment.
   */
  uint64_t fragment_length;
};
#define AAP2__DISPATCH_RESULT__NEXT_HOP_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__dispatch_result__next_hop_entry__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0 }


/*
 * Representation of a result of a Bundle Dispatcher Module (BDM).
 */
struct  Aap2__DispatchResult
{
  ProtobufCMessage base;
  /*
   * The next hop node for the bundle, which must be directly connected.
   * If more than one next hop is specified, the bundle will be replicated
   * among all of those nodes.
   * If empty, the bundle will be dropped as the BPA is not expected to have
   * any storage by itself (see the storage concepts discussion below).
   * This way, we also do not need an "action list" as described for the
   * "Generic Bundle Forwarding Interface" paper previously, because all
   * actions can either be represented as forwarding to a specific set of
   * nodes or _not_ forwarding, i.e., the deletion of the bundle.
   * Note that proactive fragmentation is expected to be a feature of the
   * storage for now. Later, maximum link capacities may be added (see above).
   */
  size_t n_next_hops;
  Aap2__DispatchResult__NextHopEntry **next_hops;
};
#define AAP2__DISPATCH_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aap2__dispatch_result__descriptor) \
, 0,NULL }


/* Aap2__AAPMessage methods */
void   aap2__aapmessage__init
                     (Aap2__AAPMessage         *message);
size_t aap2__aapmessage__get_packed_size
                     (const Aap2__AAPMessage   *message);
size_t aap2__aapmessage__pack
                     (const Aap2__AAPMessage   *message,
                      uint8_t             *out);
size_t aap2__aapmessage__pack_to_buffer
                     (const Aap2__AAPMessage   *message,
                      ProtobufCBuffer     *buffer);
Aap2__AAPMessage *
       aap2__aapmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__aapmessage__free_unpacked
                     (Aap2__AAPMessage *message,
                      ProtobufCAllocator *allocator);
/* Aap2__Welcome methods */
void   aap2__welcome__init
                     (Aap2__Welcome         *message);
size_t aap2__welcome__get_packed_size
                     (const Aap2__Welcome   *message);
size_t aap2__welcome__pack
                     (const Aap2__Welcome   *message,
                      uint8_t             *out);
size_t aap2__welcome__pack_to_buffer
                     (const Aap2__Welcome   *message,
                      ProtobufCBuffer     *buffer);
Aap2__Welcome *
       aap2__welcome__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__welcome__free_unpacked
                     (Aap2__Welcome *message,
                      ProtobufCAllocator *allocator);
/* Aap2__ConnectionConfig methods */
void   aap2__connection_config__init
                     (Aap2__ConnectionConfig         *message);
size_t aap2__connection_config__get_packed_size
                     (const Aap2__ConnectionConfig   *message);
size_t aap2__connection_config__pack
                     (const Aap2__ConnectionConfig   *message,
                      uint8_t             *out);
size_t aap2__connection_config__pack_to_buffer
                     (const Aap2__ConnectionConfig   *message,
                      ProtobufCBuffer     *buffer);
Aap2__ConnectionConfig *
       aap2__connection_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__connection_config__free_unpacked
                     (Aap2__ConnectionConfig *message,
                      ProtobufCAllocator *allocator);
/* Aap2__BundleADU methods */
void   aap2__bundle_adu__init
                     (Aap2__BundleADU         *message);
size_t aap2__bundle_adu__get_packed_size
                     (const Aap2__BundleADU   *message);
size_t aap2__bundle_adu__pack
                     (const Aap2__BundleADU   *message,
                      uint8_t             *out);
size_t aap2__bundle_adu__pack_to_buffer
                     (const Aap2__BundleADU   *message,
                      ProtobufCBuffer     *buffer);
Aap2__BundleADU *
       aap2__bundle_adu__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__bundle_adu__free_unpacked
                     (Aap2__BundleADU *message,
                      ProtobufCAllocator *allocator);
/* Aap2__Bundle methods */
void   aap2__bundle__init
                     (Aap2__Bundle         *message);
size_t aap2__bundle__get_packed_size
                     (const Aap2__Bundle   *message);
size_t aap2__bundle__pack
                     (const Aap2__Bundle   *message,
                      uint8_t             *out);
size_t aap2__bundle__pack_to_buffer
                     (const Aap2__Bundle   *message,
                      ProtobufCBuffer     *buffer);
Aap2__Bundle *
       aap2__bundle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__bundle__free_unpacked
                     (Aap2__Bundle *message,
                      ProtobufCAllocator *allocator);
/* Aap2__BundleDispatchInfo methods */
void   aap2__bundle_dispatch_info__init
                     (Aap2__BundleDispatchInfo         *message);
size_t aap2__bundle_dispatch_info__get_packed_size
                     (const Aap2__BundleDispatchInfo   *message);
size_t aap2__bundle_dispatch_info__pack
                     (const Aap2__BundleDispatchInfo   *message,
                      uint8_t             *out);
size_t aap2__bundle_dispatch_info__pack_to_buffer
                     (const Aap2__BundleDispatchInfo   *message,
                      ProtobufCBuffer     *buffer);
Aap2__BundleDispatchInfo *
       aap2__bundle_dispatch_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__bundle_dispatch_info__free_unpacked
                     (Aap2__BundleDispatchInfo *message,
                      ProtobufCAllocator *allocator);
/* Aap2__DispatchEvent methods */
void   aap2__dispatch_event__init
                     (Aap2__DispatchEvent         *message);
size_t aap2__dispatch_event__get_packed_size
                     (const Aap2__DispatchEvent   *message);
size_t aap2__dispatch_event__pack
                     (const Aap2__DispatchEvent   *message,
                      uint8_t             *out);
size_t aap2__dispatch_event__pack_to_buffer
                     (const Aap2__DispatchEvent   *message,
                      ProtobufCBuffer     *buffer);
Aap2__DispatchEvent *
       aap2__dispatch_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__dispatch_event__free_unpacked
                     (Aap2__DispatchEvent *message,
                      ProtobufCAllocator *allocator);
/* Aap2__Link methods */
void   aap2__link__init
                     (Aap2__Link         *message);
size_t aap2__link__get_packed_size
                     (const Aap2__Link   *message);
size_t aap2__link__pack
                     (const Aap2__Link   *message,
                      uint8_t             *out);
size_t aap2__link__pack_to_buffer
                     (const Aap2__Link   *message,
                      ProtobufCBuffer     *buffer);
Aap2__Link *
       aap2__link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__link__free_unpacked
                     (Aap2__Link *message,
                      ProtobufCAllocator *allocator);
/* Aap2__Keepalive methods */
void   aap2__keepalive__init
                     (Aap2__Keepalive         *message);
size_t aap2__keepalive__get_packed_size
                     (const Aap2__Keepalive   *message);
size_t aap2__keepalive__pack
                     (const Aap2__Keepalive   *message,
                      uint8_t             *out);
size_t aap2__keepalive__pack_to_buffer
                     (const Aap2__Keepalive   *message,
                      ProtobufCBuffer     *buffer);
Aap2__Keepalive *
       aap2__keepalive__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__keepalive__free_unpacked
                     (Aap2__Keepalive *message,
                      ProtobufCAllocator *allocator);
/* Aap2__AAPResponse methods */
void   aap2__aapresponse__init
                     (Aap2__AAPResponse         *message);
size_t aap2__aapresponse__get_packed_size
                     (const Aap2__AAPResponse   *message);
size_t aap2__aapresponse__pack
                     (const Aap2__AAPResponse   *message,
                      uint8_t             *out);
size_t aap2__aapresponse__pack_to_buffer
                     (const Aap2__AAPResponse   *message,
                      ProtobufCBuffer     *buffer);
Aap2__AAPResponse *
       aap2__aapresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__aapresponse__free_unpacked
                     (Aap2__AAPResponse *message,
                      ProtobufCAllocator *allocator);
/* Aap2__DispatchResult__NextHopEntry methods */
void   aap2__dispatch_result__next_hop_entry__init
                     (Aap2__DispatchResult__NextHopEntry         *message);
/* Aap2__DispatchResult methods */
void   aap2__dispatch_result__init
                     (Aap2__DispatchResult         *message);
size_t aap2__dispatch_result__get_packed_size
                     (const Aap2__DispatchResult   *message);
size_t aap2__dispatch_result__pack
                     (const Aap2__DispatchResult   *message,
                      uint8_t             *out);
size_t aap2__dispatch_result__pack_to_buffer
                     (const Aap2__DispatchResult   *message,
                      ProtobufCBuffer     *buffer);
Aap2__DispatchResult *
       aap2__dispatch_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aap2__dispatch_result__free_unpacked
                     (Aap2__DispatchResult *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Aap2__AAPMessage_Closure)
                 (const Aap2__AAPMessage *message,
                  void *closure_data);
typedef void (*Aap2__Welcome_Closure)
                 (const Aap2__Welcome *message,
                  void *closure_data);
typedef void (*Aap2__ConnectionConfig_Closure)
                 (const Aap2__ConnectionConfig *message,
                  void *closure_data);
typedef void (*Aap2__BundleADU_Closure)
                 (const Aap2__BundleADU *message,
                  void *closure_data);
typedef void (*Aap2__Bundle_Closure)
                 (const Aap2__Bundle *message,
                  void *closure_data);
typedef void (*Aap2__BundleDispatchInfo_Closure)
                 (const Aap2__BundleDispatchInfo *message,
                  void *closure_data);
typedef void (*Aap2__DispatchEvent_Closure)
                 (const Aap2__DispatchEvent *message,
                  void *closure_data);
typedef void (*Aap2__Link_Closure)
                 (const Aap2__Link *message,
                  void *closure_data);
typedef void (*Aap2__Keepalive_Closure)
                 (const Aap2__Keepalive *message,
                  void *closure_data);
typedef void (*Aap2__AAPResponse_Closure)
                 (const Aap2__AAPResponse *message,
                  void *closure_data);
typedef void (*Aap2__DispatchResult__NextHopEntry_Closure)
                 (const Aap2__DispatchResult__NextHopEntry *message,
                  void *closure_data);
typedef void (*Aap2__DispatchResult_Closure)
                 (const Aap2__DispatchResult *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    aap2__auth_type__descriptor;
extern const ProtobufCEnumDescriptor    aap2__bundle_aduflags__descriptor;
extern const ProtobufCEnumDescriptor    aap2__dispatch_reason__descriptor;
extern const ProtobufCEnumDescriptor    aap2__link_status__descriptor;
extern const ProtobufCEnumDescriptor    aap2__link_flags__descriptor;
extern const ProtobufCEnumDescriptor    aap2__response_status__descriptor;
extern const ProtobufCMessageDescriptor aap2__aapmessage__descriptor;
extern const ProtobufCMessageDescriptor aap2__welcome__descriptor;
extern const ProtobufCMessageDescriptor aap2__connection_config__descriptor;
extern const ProtobufCMessageDescriptor aap2__bundle_adu__descriptor;
extern const ProtobufCMessageDescriptor aap2__bundle__descriptor;
extern const ProtobufCMessageDescriptor aap2__bundle_dispatch_info__descriptor;
extern const ProtobufCMessageDescriptor aap2__dispatch_event__descriptor;
extern const ProtobufCMessageDescriptor aap2__link__descriptor;
extern const ProtobufCMessageDescriptor aap2__keepalive__descriptor;
extern const ProtobufCMessageDescriptor aap2__aapresponse__descriptor;
extern const ProtobufCMessageDescriptor aap2__dispatch_result__descriptor;
extern const ProtobufCMessageDescriptor aap2__dispatch_result__next_hop_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2faap2_2eproto__INCLUDED */
